flask:
  port: 8080
  host: "0.0.0.0"
email:
  from: "ReportingApp@fractracker.org"
  to:
    co: "dnr_cogcc.complaints@state.co.us"
    ky: "burnlaw@ky.gov"
    ne: "NDEQ.problem@nebraska.gov"
    nd: "AirQuality@nd.gov"
    tn: "TDEC@tn.gov"
    wv: "Wanda.E.Spradling@wv.gov"
cloud:
  bucket_name: "fractracker"
  blob_name: "report_submissions_metadata"
paths:
  metadata: "data/report_submissions_metadata.csv"
  cloud_metadata: "data/report_submissions_metadata_cloud.csv"
dates:
  begin_date: '12-01-2017'
  end_date: '01-01-2018'